Repository all-contributors/all-contributors, pull requests merged in 2019-02, with the labels that each got.

#170 docs(contribute): added more content for translations
  docs/project/contribute.md
Labels: documentation, priority: high, status: review needed

#174 Update README.md for fixed typo "ch-CN" to "zh-CN"
  README.md
Labels: documentation, status: accepted

#178 docs(contribute): added commit section
  docs/project/contribute.md
Labels: documentation, priority: low

#222 docs(MAINTAINERS): typo fix
  MAINTAINERS.md
Labels: documentation

#220 docs(contribute): minor rectifications
  docs/project/contribute.md
Labels: documentation, priority: medium, status: review needed
