Repository all-contributors/all-contributors, pull requests merged in 2019-03, with the labels that each got.

#199 feat(emoji-key): added Project Manager
  docs/emoji-key.md
Labels: enhancement, priority: medium, status: review needed

#238 docs(contribute): improved translation section
  docs/project/contribute.md
Labels: documentation, priority: medium, status: accepted

#206 fix: show Algolia logo on search dropdown
  package.json
  website/static/css/docs.css
  yarn.lock
Labels: status: review needed
